### ISSUE TITLE
Drop supporting Sphinx 3.x for future 

### ISSUE THREAD

**Issue by attakei** [attakei/sphinx-revealjs#128]
## Reasons

- Sphinx 3.x is not for Python 3.10.x (current stable)
- These versions do not have compatibility for latest deps(ex: Jinja2 and MarkupSafe)
- Need simplify dependencies to migrate flit as packaging (See [this commit](https://github.com/attakei/sphinx-revealjs/commit/2fe4b7b9504c4d00deebe3f31ece64d1f7833260) and [branch](https://github.com/attakei/sphinx-revealjs/tree/update/use-flit))

## Tasks

- [x] Add deprecated message in version 2.x (with sphinx-revealjs 2.6)
- [x] Add warning to reccomend message for updating Sphinx (with sphinx-revealjs 2.8) 
- [x] Lock dependencies by versioning (`Sphinx>=4.0`) ( (with sphinx-revealjs 3.0)

**Comment by attakei** [comment]
Released implements by v3.0.0
