### ISSUE TITLE
Drop supporting Python 3.6

### ISSUE THREAD

**Issue by attakei** [attakei/sphinx-revealjs#132]
## Reasons

- CPython 3.6 is released final security-only release (ref: [PEP494](https://peps.python.org/pep-0494/))
- More than 3 months is passed after marked deprecated notice for dropping support Python 3.6.

## Note

This is only removing support target. Users can install with Python 3.6 too. 

## Tasks

- [x] Remove Python 3.6 conditions from testcases
- [x] Remove Python 3.6 from classifiers
- [x] Change loglevel for drop supporting Pyhton 3.6 (info -> warning)

**Comment by attakei** [comment]
Released by 2.4.0
