### ISSUE TITLE
Update Reveal.js and components for 4.5.0

### ISSUE THREAD

**Issue by attakei** [attakei/sphinx-revealjs#140]
## Tasks 

- [x] List features for behavior
  - [x] Check that `revealjs-fragments` need support for `.custom` class
- [x] Update dependencies
- [x] Implement all features (TODO: add nested list into there)
- [x] Release

Ref: https://github.com/hakimel/reveal.js/releases/tag/4.5.0

**Comment by attakei** [comment]
> Add support for jump-to-slide! 🚀 Press the G key and type a slide number or title.

JavaScript behavior. We can use it on import

**Comment by attakei** [comment]
Release as [v2.6.0](https://github.com/attakei/sphinx-revealjs/releases/tag/v2.6.0)
